// data/codes.ts
// The seed code spine for the Sydra IDR page surface.
//
// SOURCE OF TRUTH: in production this table is seeded from (a) the CMS Federal IDR
// Public Use Files most-disputed surgical services and (b) Sydra's own claim
// history. The list below is the launch spine across the four Sydra specialties.
// Add rows as the PUF reveals new disputed codes; the architecture does not change.
//
// LICENSING: every `codeType: "CPT"` row is AMA copyrighted at the descriptor level.
// `name` and `shortDescription` below are ORIGINAL plain-language wording written
// for Sydra, NOT the AMA long descriptor, so they are safe to publish before the
// AMA distribution license is in place. Do not swap in AMA descriptors until the
// license is signed. `codeType: "HCPCS"` rows are public domain.
//
// DOLLAR DATA: there are intentionally NO dollar figures in this file. Per-payer
// QPA, allowed amounts, and Medicare benchmarks are bound at render time from the
// `idr_benchmarks` Postgres table fed by the Transparency in Coverage and CMS
// Physician Fee Schedule ETL. Never hardcode a dollar value here.

export type SourceSpecialty = "spine" | "ortho" | "neuro" | "plastics" | "pain";

export interface SourceCode {
  code: string;
  codeType: "CPT" | "HCPCS";
  slug: string;            // url segment, e.g. "63047"
  name: string;            // plain-language procedure name (license-safe)
  shortDescription: string;// original wording, never the AMA descriptor
  specialty: SourceSpecialty;
  bodyRegion: string;
  setting: string;         // typical site of service
  addOn: boolean;          // add-on code, billed alongside a primary
  relatedCodes: string[];
  disputeContext: string;  // why this is disputed out of network
  valueTier: "high" | "medium" | "standard"; // INTERNAL prioritization heuristic, not published
}

export const SOURCE_CODES: SourceCode[] = [
  // ---------------------------------------------------------------- SPINE: fusion + instrumentation
  { code: "22551", codeType: "CPT", slug: "22551", name: "Anterior cervical discectomy and fusion, single level",
    shortDescription: "Removal of a cervical disc from the front of the neck with fusion of the two vertebrae at one level.",
    specialty: "spine", bodyRegion: "cervical spine", setting: "hospital or ASC", addOn: false,
    relatedCodes: ["22552", "22845", "22853"], disputeContext: "High relative value spine procedure frequently performed out of network by independent neurosurgery and orthopedic spine practices.", valueTier: "high" },
  { code: "22552", codeType: "CPT", slug: "22552", name: "Anterior cervical fusion, each additional level",
    shortDescription: "Add-on for each additional cervical interspace fused from the front during the same session.",
    specialty: "spine", bodyRegion: "cervical spine", setting: "hospital or ASC", addOn: true,
    relatedCodes: ["22551"], disputeContext: "Add-on stacked onto multi-level cervical fusions; underpayment compounds per level.", valueTier: "high" },
  { code: "22612", codeType: "CPT", slug: "22612", name: "Posterior lumbar fusion, single level",
    shortDescription: "Fusion of two lumbar vertebrae from the back at one level.",
    specialty: "spine", bodyRegion: "lumbar spine", setting: "hospital", addOn: false,
    relatedCodes: ["22614", "22842", "63047"], disputeContext: "Core lumbar fusion code with large award spreads when underpaid out of network.", valueTier: "high" },
  { code: "22630", codeType: "CPT", slug: "22630", name: "Posterior lumbar interbody fusion (PLIF), single level",
    shortDescription: "Lumbar fusion at one level using an interbody device placed from the back.",
    specialty: "spine", bodyRegion: "lumbar spine", setting: "hospital", addOn: false,
    relatedCodes: ["22632", "22853", "22842"], disputeContext: "Interbody fusion, high device and surgical value, common underpayment target.", valueTier: "high" },
  { code: "22633", codeType: "CPT", slug: "22633", name: "Transforaminal lumbar interbody fusion (TLIF), single level",
    shortDescription: "Combined posterior and interbody lumbar fusion at one level through a transforaminal approach.",
    specialty: "spine", bodyRegion: "lumbar spine", setting: "hospital", addOn: false,
    relatedCodes: ["22634", "22842", "63047"], disputeContext: "One of the most disputed spine codes; large QPA-to-award spread in surgical IDR data.", valueTier: "high" },
  { code: "22634", codeType: "CPT", slug: "22634", name: "TLIF, each additional level",
    shortDescription: "Add-on for each additional level of combined posterior and interbody lumbar fusion.",
    specialty: "spine", bodyRegion: "lumbar spine", setting: "hospital", addOn: true,
    relatedCodes: ["22633"], disputeContext: "Per-level add-on; multi-level cases magnify the underpayment.", valueTier: "high" },
  { code: "22842", codeType: "CPT", slug: "22842", name: "Posterior spinal instrumentation, 3 to 6 segments",
    shortDescription: "Placement of posterior rods and screws spanning three to six spinal segments.",
    specialty: "spine", bodyRegion: "spine", setting: "hospital", addOn: true,
    relatedCodes: ["22612", "22633", "22845"], disputeContext: "Hardware-heavy add-on with significant value; routinely bundled and underpaid.", valueTier: "high" },
  { code: "22845", codeType: "CPT", slug: "22845", name: "Anterior spinal instrumentation, 2 to 3 segments",
    shortDescription: "Placement of anterior plates or rods spanning two to three spinal segments.",
    specialty: "spine", bodyRegion: "spine", setting: "hospital", addOn: true,
    relatedCodes: ["22551", "22853"], disputeContext: "Anterior hardware add-on, common in cervical and thoracolumbar fusions.", valueTier: "high" },
  { code: "22853", codeType: "CPT", slug: "22853", name: "Interbody device insertion with integral anterior instrumentation",
    shortDescription: "Insertion of an interbody cage that carries its own anterior fixation, per interspace.",
    specialty: "spine", bodyRegion: "spine", setting: "hospital", addOn: true,
    relatedCodes: ["22630", "22633"], disputeContext: "Device add-on; high implant value drives large dollar disputes.", valueTier: "high" },
  { code: "22854", codeType: "CPT", slug: "22854", name: "Interbody device insertion into corpectomy defect",
    shortDescription: "Placement of a structural device into the space left after a vertebral body removal.",
    specialty: "spine", bodyRegion: "spine", setting: "hospital", addOn: true,
    relatedCodes: ["22853"], disputeContext: "High-acuity reconstruction add-on, frequently underpaid.", valueTier: "high" },
  { code: "22614", codeType: "CPT", slug: "22614", name: "Posterior spinal fusion, each additional level",
    shortDescription: "Add-on for each additional vertebral level fused from the back.",
    specialty: "spine", bodyRegion: "spine", setting: "hospital", addOn: true,
    relatedCodes: ["22612", "22633"], disputeContext: "Per-level fusion add-on compounding multi-level underpayment.", valueTier: "high" },

  // ---------------------------------------------------------------- SPINE: decompression
  { code: "63030", codeType: "CPT", slug: "63030", name: "Lumbar discectomy / laminotomy, single interspace",
    shortDescription: "Removal of a herniated lumbar disc with partial bone removal to free the nerve root, at one interspace.",
    specialty: "spine", bodyRegion: "lumbar spine", setting: "hospital or ASC", addOn: false,
    relatedCodes: ["63035", "63047"], disputeContext: "Very high volume disc surgery; one of the most searched spine codes.", valueTier: "high" },
  { code: "63035", codeType: "CPT", slug: "63035", name: "Lumbar discectomy, each additional interspace",
    shortDescription: "Add-on for each additional interspace decompressed during the same discectomy.",
    specialty: "spine", bodyRegion: "lumbar spine", setting: "hospital or ASC", addOn: true,
    relatedCodes: ["63030"], disputeContext: "Per-level add-on routinely bundled away by payers.", valueTier: "medium" },
  { code: "63042", codeType: "CPT", slug: "63042", name: "Repeat lumbar discectomy, single interspace",
    shortDescription: "Re-exploration and disc removal at a previously operated lumbar interspace.",
    specialty: "spine", bodyRegion: "lumbar spine", setting: "hospital", addOn: false,
    relatedCodes: ["63030"], disputeContext: "Revision complexity; payers undervalue reoperation work.", valueTier: "high" },
  { code: "63045", codeType: "CPT", slug: "63045", name: "Cervical laminectomy with foraminotomy, single segment",
    shortDescription: "Bone removal to decompress the cervical spinal cord and nerve roots at one segment.",
    specialty: "spine", bodyRegion: "cervical spine", setting: "hospital", addOn: false,
    relatedCodes: ["63048", "63047"], disputeContext: "High value cervical decompression, common OON dispute.", valueTier: "high" },
  { code: "63047", codeType: "CPT", slug: "63047", name: "Lumbar laminectomy with foraminotomy, single segment",
    shortDescription: "Bone removal to decompress lumbar nerve roots and the central canal at one segment.",
    specialty: "spine", bodyRegion: "lumbar spine", setting: "hospital or ASC", addOn: false,
    relatedCodes: ["63048", "63030", "22633"], disputeContext: "Flagship high-volume lumbar decompression code; anchor page for the surface.", valueTier: "high" },
  { code: "63048", codeType: "CPT", slug: "63048", name: "Laminectomy with foraminotomy, each additional segment",
    shortDescription: "Add-on for each additional segment decompressed during the same laminectomy.",
    specialty: "spine", bodyRegion: "spine", setting: "hospital or ASC", addOn: true,
    relatedCodes: ["63047", "63045"], disputeContext: "Per-segment add-on; multi-level stenosis cases magnify the dispute.", valueTier: "medium" },
  { code: "63056", codeType: "CPT", slug: "63056", name: "Transpedicular lumbar decompression, single segment",
    shortDescription: "Decompression of the lumbar canal or nerve through the pedicle at one segment.",
    specialty: "spine", bodyRegion: "lumbar spine", setting: "hospital", addOn: false,
    relatedCodes: ["63047"], disputeContext: "Used for far-lateral and fracture decompression; high acuity.", valueTier: "high" },
  { code: "63075", codeType: "CPT", slug: "63075", name: "Anterior cervical discectomy without fusion, single interspace",
    shortDescription: "Removal of a cervical disc from the front of the neck at one interspace without fusion.",
    specialty: "spine", bodyRegion: "cervical spine", setting: "hospital or ASC", addOn: false,
    relatedCodes: ["22551", "63076"], disputeContext: "Often paired with fusion codes; disputed when unbundled.", valueTier: "medium" },

  // ---------------------------------------------------------------- SPINE / PAIN: injections + ablation
  { code: "62321", codeType: "CPT", slug: "62321", name: "Cervical or thoracic epidural injection with imaging",
    shortDescription: "Image-guided epidural steroid injection in the neck or mid back.",
    specialty: "pain", bodyRegion: "cervical/thoracic spine", setting: "ASC or office", addOn: false,
    relatedCodes: ["62323", "64490"], disputeContext: "High frequency interventional pain service; small per-claim dollars but large volume.", valueTier: "standard" },
  { code: "62323", codeType: "CPT", slug: "62323", name: "Lumbar or sacral epidural injection with imaging",
    shortDescription: "Image-guided epidural steroid injection in the low back.",
    specialty: "pain", bodyRegion: "lumbar/sacral spine", setting: "ASC or office", addOn: false,
    relatedCodes: ["62321", "64483"], disputeContext: "Very high volume pain procedure; volume drives the page demand.", valueTier: "standard" },
  { code: "64483", codeType: "CPT", slug: "64483", name: "Transforaminal epidural injection, lumbar, single level",
    shortDescription: "Targeted steroid injection around a single lumbar nerve root through the foramen.",
    specialty: "pain", bodyRegion: "lumbar spine", setting: "ASC or office", addOn: false,
    relatedCodes: ["64484", "62323"], disputeContext: "Workhorse interventional pain code; frequently underpaid out of network.", valueTier: "standard" },
  { code: "64484", codeType: "CPT", slug: "64484", name: "Transforaminal epidural injection, lumbar, each additional level",
    shortDescription: "Add-on for each additional lumbar nerve root injected in the same session.",
    specialty: "pain", bodyRegion: "lumbar spine", setting: "ASC or office", addOn: true,
    relatedCodes: ["64483"], disputeContext: "Per-level add-on; bundled and reduced by payers.", valueTier: "standard" },
  { code: "64490", codeType: "CPT", slug: "64490", name: "Facet joint injection, cervical or thoracic, single level",
    shortDescription: "Injection into or around a neck or mid back facet joint at one level.",
    specialty: "pain", bodyRegion: "cervical/thoracic spine", setting: "ASC or office", addOn: false,
    relatedCodes: ["64493", "64633"], disputeContext: "Common diagnostic and therapeutic facet procedure.", valueTier: "standard" },
  { code: "64493", codeType: "CPT", slug: "64493", name: "Facet joint injection, lumbar or sacral, single level",
    shortDescription: "Injection into or around a low back facet joint at one level.",
    specialty: "pain", bodyRegion: "lumbar/sacral spine", setting: "ASC or office", addOn: false,
    relatedCodes: ["64490", "64635"], disputeContext: "High volume low back pain procedure.", valueTier: "standard" },
  { code: "64633", codeType: "CPT", slug: "64633", name: "Facet joint radiofrequency ablation, cervical or thoracic, single",
    shortDescription: "Heat lesioning of the nerve to a neck or mid back facet joint at one level.",
    specialty: "pain", bodyRegion: "cervical/thoracic spine", setting: "ASC", addOn: false,
    relatedCodes: ["64635", "64490"], disputeContext: "Higher value ablation; frequent prior-auth and payment disputes.", valueTier: "medium" },
  { code: "64635", codeType: "CPT", slug: "64635", name: "Facet joint radiofrequency ablation, lumbar or sacral, single",
    shortDescription: "Heat lesioning of the nerve to a low back facet joint at one level.",
    specialty: "pain", bodyRegion: "lumbar/sacral spine", setting: "ASC", addOn: false,
    relatedCodes: ["64636", "64493"], disputeContext: "Common low back ablation; underpayment is routine out of network.", valueTier: "medium" },
  { code: "64636", codeType: "CPT", slug: "64636", name: "Facet joint radiofrequency ablation, each additional level",
    shortDescription: "Add-on for each additional facet level ablated in the same session.",
    specialty: "pain", bodyRegion: "spine", setting: "ASC", addOn: true,
    relatedCodes: ["64635"], disputeContext: "Per-level add-on stacked on multi-level ablations.", valueTier: "standard" },

  // ---------------------------------------------------------------- SPINE: neurostimulation
  { code: "63650", codeType: "CPT", slug: "63650", name: "Spinal cord stimulator electrode placement, percutaneous",
    shortDescription: "Percutaneous placement of a neurostimulator lead in the epidural space.",
    specialty: "spine", bodyRegion: "spine", setting: "ASC or hospital", addOn: false,
    relatedCodes: ["63685", "63655"], disputeContext: "High device value; payers aggressively manage and underpay.", valueTier: "high" },
  { code: "63655", codeType: "CPT", slug: "63655", name: "Spinal cord stimulator electrode placement, laminectomy",
    shortDescription: "Open placement of a paddle neurostimulator electrode via laminectomy.",
    specialty: "spine", bodyRegion: "spine", setting: "hospital", addOn: false,
    relatedCodes: ["63650", "63685"], disputeContext: "Surgical paddle lead placement; high acuity and value.", valueTier: "high" },
  { code: "63685", codeType: "CPT", slug: "63685", name: "Spinal cord stimulator generator insertion",
    shortDescription: "Insertion or replacement of the implantable pulse generator that powers the stimulator.",
    specialty: "spine", bodyRegion: "spine", setting: "ASC or hospital", addOn: false,
    relatedCodes: ["63650", "63655"], disputeContext: "Implant-heavy; large dollar disputes when paid below cost.", valueTier: "high" },

  // ---------------------------------------------------------------- ORTHO: arthroplasty
  { code: "27130", codeType: "CPT", slug: "27130", name: "Total hip replacement",
    shortDescription: "Replacement of the hip joint with prosthetic components.",
    specialty: "ortho", bodyRegion: "hip", setting: "hospital or ASC", addOn: false,
    relatedCodes: ["27125", "27132"], disputeContext: "High volume joint replacement; large award spreads out of network.", valueTier: "high" },
  { code: "27125", codeType: "CPT", slug: "27125", name: "Partial hip replacement (hemiarthroplasty)",
    shortDescription: "Replacement of the femoral head only, often after a hip fracture.",
    specialty: "ortho", bodyRegion: "hip", setting: "hospital", addOn: false,
    relatedCodes: ["27130", "27236"], disputeContext: "Common fracture-related arthroplasty.", valueTier: "medium" },
  { code: "27132", codeType: "CPT", slug: "27132", name: "Conversion to total hip replacement",
    shortDescription: "Conversion of a prior hip procedure to a total hip replacement.",
    specialty: "ortho", bodyRegion: "hip", setting: "hospital", addOn: false,
    relatedCodes: ["27130"], disputeContext: "Revision-level complexity, undervalued by payers.", valueTier: "high" },
  { code: "27447", codeType: "CPT", slug: "27447", name: "Total knee replacement",
    shortDescription: "Replacement of the knee joint surfaces with prosthetic components.",
    specialty: "ortho", bodyRegion: "knee", setting: "hospital or ASC", addOn: false,
    relatedCodes: ["27446", "27486"], disputeContext: "One of the highest volume surgical codes in the country; major page demand.", valueTier: "high" },
  { code: "27446", codeType: "CPT", slug: "27446", name: "Partial knee replacement",
    shortDescription: "Replacement of one compartment of the knee joint.",
    specialty: "ortho", bodyRegion: "knee", setting: "ASC or hospital", addOn: false,
    relatedCodes: ["27447"], disputeContext: "Growing ASC volume; disputed reimbursement out of network.", valueTier: "medium" },
  { code: "27486", codeType: "CPT", slug: "27486", name: "Knee replacement revision, one component",
    shortDescription: "Revision of one component of a previously replaced knee.",
    specialty: "ortho", bodyRegion: "knee", setting: "hospital", addOn: false,
    relatedCodes: ["27447", "27487"], disputeContext: "Revision complexity, high value, frequent underpayment.", valueTier: "high" },
  { code: "27487", codeType: "CPT", slug: "27487", name: "Knee replacement revision, femoral and tibial",
    shortDescription: "Revision of both major components of a previously replaced knee.",
    specialty: "ortho", bodyRegion: "knee", setting: "hospital", addOn: false,
    relatedCodes: ["27486"], disputeContext: "Highest-acuity knee revision; large dollar disputes.", valueTier: "high" },
  { code: "23472", codeType: "CPT", slug: "23472", name: "Total shoulder replacement",
    shortDescription: "Replacement of the shoulder joint, anatomic or reverse.",
    specialty: "ortho", bodyRegion: "shoulder", setting: "hospital or ASC", addOn: false,
    relatedCodes: ["23474"], disputeContext: "Rising volume joint replacement; high device value.", valueTier: "high" },
  { code: "23474", codeType: "CPT", slug: "23474", name: "Shoulder replacement revision",
    shortDescription: "Revision of a previously replaced shoulder joint.",
    specialty: "ortho", bodyRegion: "shoulder", setting: "hospital", addOn: false,
    relatedCodes: ["23472"], disputeContext: "Revision complexity, undervalued out of network.", valueTier: "high" },
  { code: "24363", codeType: "CPT", slug: "24363", name: "Total elbow replacement",
    shortDescription: "Replacement of the elbow joint with prosthetic components.",
    specialty: "ortho", bodyRegion: "elbow", setting: "hospital", addOn: false,
    relatedCodes: [], disputeContext: "Lower volume but high value reconstruction.", valueTier: "high" },

  // ---------------------------------------------------------------- ORTHO: arthroscopy
  { code: "29881", codeType: "CPT", slug: "29881", name: "Knee arthroscopy with meniscectomy",
    shortDescription: "Arthroscopic trimming or removal of torn meniscus in one compartment of the knee.",
    specialty: "ortho", bodyRegion: "knee", setting: "ASC", addOn: false,
    relatedCodes: ["29880", "29877"], disputeContext: "Extremely high volume ASC procedure; strong long-tail demand.", valueTier: "medium" },
  { code: "29880", codeType: "CPT", slug: "29880", name: "Knee arthroscopy with meniscectomy, both compartments",
    shortDescription: "Arthroscopic meniscus surgery in both the medial and lateral compartments.",
    specialty: "ortho", bodyRegion: "knee", setting: "ASC", addOn: false,
    relatedCodes: ["29881"], disputeContext: "Common knee scope variant; disputed when downcoded.", valueTier: "medium" },
  { code: "29827", codeType: "CPT", slug: "29827", name: "Shoulder arthroscopy with rotator cuff repair",
    shortDescription: "Arthroscopic repair of a torn rotator cuff.",
    specialty: "ortho", bodyRegion: "shoulder", setting: "ASC", addOn: false,
    relatedCodes: ["29826", "29806"], disputeContext: "High volume shoulder repair; meaningful per-claim value.", valueTier: "medium" },
  { code: "29826", codeType: "CPT", slug: "29826", name: "Shoulder arthroscopy with subacromial decompression",
    shortDescription: "Add-on arthroscopic decompression of the space above the rotator cuff.",
    specialty: "ortho", bodyRegion: "shoulder", setting: "ASC", addOn: true,
    relatedCodes: ["29827"], disputeContext: "Add-on routinely bundled away by payers.", valueTier: "standard" },
  { code: "29806", codeType: "CPT", slug: "29806", name: "Shoulder arthroscopy with capsulorrhaphy",
    shortDescription: "Arthroscopic tightening of the shoulder capsule for instability.",
    specialty: "ortho", bodyRegion: "shoulder", setting: "ASC", addOn: false,
    relatedCodes: ["29827"], disputeContext: "Instability repair, disputed reimbursement out of network.", valueTier: "medium" },
  { code: "29888", codeType: "CPT", slug: "29888", name: "Arthroscopic ACL reconstruction",
    shortDescription: "Arthroscopic reconstruction of the anterior cruciate ligament of the knee.",
    specialty: "ortho", bodyRegion: "knee", setting: "ASC or hospital", addOn: false,
    relatedCodes: ["29881"], disputeContext: "High value sports medicine procedure; strong search volume.", valueTier: "medium" },
  { code: "29877", codeType: "CPT", slug: "29877", name: "Knee arthroscopy with chondroplasty",
    shortDescription: "Arthroscopic smoothing of damaged knee cartilage.",
    specialty: "ortho", bodyRegion: "knee", setting: "ASC", addOn: false,
    relatedCodes: ["29881"], disputeContext: "Often bundled with meniscectomy; disputed when unbundled.", valueTier: "standard" },

  // ---------------------------------------------------------------- ORTHO: fracture / trauma
  { code: "27236", codeType: "CPT", slug: "27236", name: "Hip fracture repair with replacement or fixation",
    shortDescription: "Open repair of a femoral neck fracture with fixation or prosthetic replacement.",
    specialty: "ortho", bodyRegion: "hip", setting: "hospital", addOn: false,
    relatedCodes: ["27244", "27245", "27125"], disputeContext: "Emergent trauma often delivered out of network at in-network facilities.", valueTier: "high" },
  { code: "27244", codeType: "CPT", slug: "27244", name: "Femur fracture repair with plate or screws",
    shortDescription: "Open repair of an intertrochanteric femur fracture using a plate and screw construct.",
    specialty: "ortho", bodyRegion: "hip/femur", setting: "hospital", addOn: false,
    relatedCodes: ["27245", "27236"], disputeContext: "Common trauma fixation; NSA-protected emergent context.", valueTier: "high" },
  { code: "27245", codeType: "CPT", slug: "27245", name: "Femur fracture repair with intramedullary nail",
    shortDescription: "Repair of an intertrochanteric femur fracture using a rod placed inside the bone.",
    specialty: "ortho", bodyRegion: "hip/femur", setting: "hospital", addOn: false,
    relatedCodes: ["27244"], disputeContext: "High volume hip fracture fixation.", valueTier: "high" },
  { code: "25607", codeType: "CPT", slug: "25607", name: "Wrist fracture repair, extra-articular",
    shortDescription: "Open repair of a distal radius fracture outside the joint surface.",
    specialty: "ortho", bodyRegion: "wrist", setting: "hospital or ASC", addOn: false,
    relatedCodes: ["25608", "25609"], disputeContext: "Common trauma; emergent OON exposure.", valueTier: "medium" },
  { code: "25608", codeType: "CPT", slug: "25608", name: "Wrist fracture repair, intra-articular, two fragments",
    shortDescription: "Open repair of a distal radius fracture involving two joint-surface fragments.",
    specialty: "ortho", bodyRegion: "wrist", setting: "hospital or ASC", addOn: false,
    relatedCodes: ["25607", "25609"], disputeContext: "Higher complexity wrist trauma.", valueTier: "medium" },
  { code: "25609", codeType: "CPT", slug: "25609", name: "Wrist fracture repair, intra-articular, three or more fragments",
    shortDescription: "Open repair of a complex distal radius fracture with three or more joint fragments.",
    specialty: "ortho", bodyRegion: "wrist", setting: "hospital", addOn: false,
    relatedCodes: ["25608"], disputeContext: "Most complex wrist fracture tier; undervalued by payers.", valueTier: "medium" },
  { code: "23615", codeType: "CPT", slug: "23615", name: "Shoulder fracture repair (proximal humerus)",
    shortDescription: "Open repair of a fracture of the upper arm bone at the shoulder.",
    specialty: "ortho", bodyRegion: "shoulder", setting: "hospital", addOn: false,
    relatedCodes: [], disputeContext: "Emergent trauma with NSA protection.", valueTier: "medium" },
  { code: "27759", codeType: "CPT", slug: "27759", name: "Tibia fracture repair with intramedullary nail",
    shortDescription: "Repair of a tibial shaft fracture using a rod placed inside the bone.",
    specialty: "ortho", bodyRegion: "tibia", setting: "hospital", addOn: false,
    relatedCodes: [], disputeContext: "High volume long-bone trauma fixation.", valueTier: "high" },

  // ---------------------------------------------------------------- NEURO: cranial
  { code: "61510", codeType: "CPT", slug: "61510", name: "Craniotomy for brain tumor removal, supratentorial",
    shortDescription: "Opening of the skull to remove a tumor in the upper part of the brain.",
    specialty: "neuro", bodyRegion: "brain", setting: "hospital", addOn: false,
    relatedCodes: ["61512", "61518", "69990"], disputeContext: "Among the highest value codes in medicine; large dollar IDR disputes.", valueTier: "high" },
  { code: "61512", codeType: "CPT", slug: "61512", name: "Craniotomy for meningioma removal, supratentorial",
    shortDescription: "Opening of the skull to remove a meningioma in the upper part of the brain.",
    specialty: "neuro", bodyRegion: "brain", setting: "hospital", addOn: false,
    relatedCodes: ["61510"], disputeContext: "High acuity cranial tumor surgery.", valueTier: "high" },
  { code: "61518", codeType: "CPT", slug: "61518", name: "Craniotomy for brain tumor removal, infratentorial",
    shortDescription: "Opening of the skull to remove a tumor in the lower, posterior part of the brain.",
    specialty: "neuro", bodyRegion: "brain", setting: "hospital", addOn: false,
    relatedCodes: ["61510"], disputeContext: "Posterior fossa surgery, highest complexity tier.", valueTier: "high" },
  { code: "61304", codeType: "CPT", slug: "61304", name: "Exploratory craniotomy, supratentorial",
    shortDescription: "Opening of the skull for exploration or decompression of the upper brain.",
    specialty: "neuro", bodyRegion: "brain", setting: "hospital", addOn: false,
    relatedCodes: ["61510"], disputeContext: "Emergent cranial decompression, NSA-protected.", valueTier: "high" },
  { code: "61781", codeType: "CPT", slug: "61781", name: "Stereotactic navigation, cranial, intradural",
    shortDescription: "Add-on computer-assisted navigation during cranial surgery inside the dura.",
    specialty: "neuro", bodyRegion: "brain", setting: "hospital", addOn: true,
    relatedCodes: ["61510", "61512"], disputeContext: "Navigation add-on routinely bundled and reduced.", valueTier: "medium" },
  { code: "62223", codeType: "CPT", slug: "62223", name: "Ventriculoperitoneal shunt placement",
    shortDescription: "Placement of a shunt to drain excess cerebrospinal fluid from the brain to the abdomen.",
    specialty: "neuro", bodyRegion: "brain", setting: "hospital", addOn: false,
    relatedCodes: [], disputeContext: "Common neurosurgical procedure with device value.", valueTier: "medium" },
  { code: "61154", codeType: "CPT", slug: "61154", name: "Burr hole with hematoma evacuation",
    shortDescription: "Drilling of a small skull opening to drain a collection of blood on the brain.",
    specialty: "neuro", bodyRegion: "brain", setting: "hospital", addOn: false,
    relatedCodes: ["61304"], disputeContext: "Emergent procedure delivered out of network in trauma settings.", valueTier: "medium" },
  { code: "69990", codeType: "HCPCS", slug: "69990", name: "Operating microscope use",
    shortDescription: "Add-on for use of the operating microscope when not already included in the primary procedure.",
    specialty: "neuro", bodyRegion: "n/a", setting: "hospital or ASC", addOn: true,
    relatedCodes: ["61510", "64721"], disputeContext: "Frequently denied as bundled; eligibility depends on the primary code.", valueTier: "standard" },

  // ---------------------------------------------------------------- NEURO: peripheral nerve
  { code: "64721", codeType: "CPT", slug: "64721", name: "Carpal tunnel release",
    shortDescription: "Surgical release of the median nerve at the wrist to relieve carpal tunnel syndrome.",
    specialty: "neuro", bodyRegion: "wrist", setting: "ASC or office", addOn: false,
    relatedCodes: ["64718", "69990"], disputeContext: "Very high volume nerve procedure; strong long-tail search demand.", valueTier: "medium" },
  { code: "64718", codeType: "CPT", slug: "64718", name: "Ulnar nerve release at the elbow",
    shortDescription: "Surgical release or transposition of the ulnar nerve at the elbow.",
    specialty: "neuro", bodyRegion: "elbow", setting: "ASC or hospital", addOn: false,
    relatedCodes: ["64719", "64721"], disputeContext: "Common nerve decompression, disputed out of network.", valueTier: "medium" },
  { code: "64719", codeType: "CPT", slug: "64719", name: "Ulnar nerve release at the wrist",
    shortDescription: "Surgical release of the ulnar nerve at the wrist (Guyon canal).",
    specialty: "neuro", bodyRegion: "wrist", setting: "ASC or office", addOn: false,
    relatedCodes: ["64718"], disputeContext: "Nerve decompression variant.", valueTier: "standard" },
  { code: "64708", codeType: "CPT", slug: "64708", name: "Peripheral nerve decompression, arm or leg",
    shortDescription: "Surgical decompression or repair of a major peripheral nerve in the arm or leg.",
    specialty: "neuro", bodyRegion: "extremity", setting: "ASC or hospital", addOn: false,
    relatedCodes: ["64721", "64718"], disputeContext: "Higher complexity nerve work.", valueTier: "medium" },

  // ---------------------------------------------------------------- PLASTICS: flaps, grafts, reconstruction
  { code: "15734", codeType: "CPT", slug: "15734", name: "Muscle flap, trunk",
    shortDescription: "Transfer of a muscle or muscle-and-skin flap to reconstruct a defect on the trunk.",
    specialty: "plastics", bodyRegion: "trunk", setting: "hospital", addOn: false,
    relatedCodes: ["15738", "15756"], disputeContext: "High value reconstruction; common post-trauma and post-oncologic.", valueTier: "high" },
  { code: "15738", codeType: "CPT", slug: "15738", name: "Muscle flap, lower extremity",
    shortDescription: "Transfer of a muscle or muscle-and-skin flap to reconstruct a leg defect.",
    specialty: "plastics", bodyRegion: "lower extremity", setting: "hospital", addOn: false,
    relatedCodes: ["15734"], disputeContext: "Limb salvage reconstruction; undervalued by payers.", valueTier: "high" },
  { code: "15756", codeType: "CPT", slug: "15756", name: "Free muscle flap with microvascular repair",
    shortDescription: "Transfer of a free muscle flap reconnected with microsurgical blood vessel repair.",
    specialty: "plastics", bodyRegion: "varies", setting: "hospital", addOn: false,
    relatedCodes: ["15734", "15738"], disputeContext: "Microsurgical reconstruction, highest plastics value tier.", valueTier: "high" },
  { code: "14301", codeType: "CPT", slug: "14301", name: "Tissue transfer flap, 30 sq cm or more",
    shortDescription: "Local tissue rearrangement to close a large defect, thirty square centimeters or larger.",
    specialty: "plastics", bodyRegion: "varies", setting: "hospital or ASC", addOn: false,
    relatedCodes: ["13101"], disputeContext: "Reconstruction frequently downcoded by payers.", valueTier: "medium" },
  { code: "13101", codeType: "CPT", slug: "13101", name: "Complex wound repair, trunk",
    shortDescription: "Layered repair of a complex wound on the trunk.",
    specialty: "plastics", bodyRegion: "trunk", setting: "hospital or ASC", addOn: false,
    relatedCodes: ["14301"], disputeContext: "Often delivered emergently and out of network.", valueTier: "standard" },
  { code: "19357", codeType: "CPT", slug: "19357", name: "Breast reconstruction with tissue expander",
    shortDescription: "Breast reconstruction using a tissue expander to prepare for an implant.",
    specialty: "plastics", bodyRegion: "breast", setting: "hospital", addOn: false,
    relatedCodes: ["19361", "19364"], disputeContext: "Post-mastectomy reconstruction; protected and high value.", valueTier: "high" },
  { code: "19361", codeType: "CPT", slug: "19361", name: "Breast reconstruction with latissimus flap",
    shortDescription: "Breast reconstruction using a back muscle flap.",
    specialty: "plastics", bodyRegion: "breast", setting: "hospital", addOn: false,
    relatedCodes: ["19357", "19364"], disputeContext: "Autologous reconstruction, high acuity.", valueTier: "high" },
  { code: "19364", codeType: "CPT", slug: "19364", name: "Breast reconstruction with free flap",
    shortDescription: "Breast reconstruction using a free tissue flap with microvascular repair.",
    specialty: "plastics", bodyRegion: "breast", setting: "hospital", addOn: false,
    relatedCodes: ["19361"], disputeContext: "Microsurgical breast reconstruction; large dollar disputes.", valueTier: "high" },
  { code: "19367", codeType: "CPT", slug: "19367", name: "Breast reconstruction with TRAM flap",
    shortDescription: "Breast reconstruction using lower abdominal tissue on a muscle pedicle.",
    specialty: "plastics", bodyRegion: "breast", setting: "hospital", addOn: false,
    relatedCodes: ["19364"], disputeContext: "Autologous reconstruction frequently underpaid.", valueTier: "high" },
  // ================================================================ EXPANSION SET
  // ---------------------------------------------------------------- SPINE: anterior + deformity + corpectomy
  { code: "22558", codeType: "CPT", slug: "22558", name: "Anterior lumbar interbody fusion (ALIF), single level",
    shortDescription: "Fusion of two lumbar vertebrae from the front using an interbody device at one level.",
    specialty: "spine", bodyRegion: "lumbar spine", setting: "hospital", addOn: false,
    relatedCodes: ["22585", "22845", "22853"], disputeContext: "High value anterior fusion frequently performed out of network; large award spreads.", valueTier: "high" },
  { code: "22585", codeType: "CPT", slug: "22585", name: "Anterior interbody fusion, each additional level",
    shortDescription: "Add-on for each additional interspace fused from the front during the same session.",
    specialty: "spine", bodyRegion: "spine", setting: "hospital", addOn: true,
    relatedCodes: ["22558"], disputeContext: "Per-level anterior add-on; multi-level cases compound the underpayment.", valueTier: "high" },
  { code: "22600", codeType: "CPT", slug: "22600", name: "Posterior cervical fusion, single level",
    shortDescription: "Fusion of two cervical vertebrae from the back at one level.",
    specialty: "spine", bodyRegion: "cervical spine", setting: "hospital", addOn: false,
    relatedCodes: ["22614", "22842"], disputeContext: "Posterior cervical fusion, high value, common out of network dispute.", valueTier: "high" },
  { code: "22610", codeType: "CPT", slug: "22610", name: "Posterior thoracic fusion, single level",
    shortDescription: "Fusion of two thoracic vertebrae from the back at one level.",
    specialty: "spine", bodyRegion: "thoracic spine", setting: "hospital", addOn: false,
    relatedCodes: ["22614", "22842"], disputeContext: "Thoracic fusion with significant value.", valueTier: "high" },
  { code: "22632", codeType: "CPT", slug: "22632", name: "Posterior interbody fusion, each additional level",
    shortDescription: "Add-on for each additional interbody level fused from the back.",
    specialty: "spine", bodyRegion: "lumbar spine", setting: "hospital", addOn: true,
    relatedCodes: ["22630"], disputeContext: "Per-level interbody add-on, routinely bundled.", valueTier: "high" },
  { code: "22800", codeType: "CPT", slug: "22800", name: "Posterior fusion for spinal deformity, up to 6 segments",
    shortDescription: "Posterior fusion to correct a spinal deformity spanning up to six segments.",
    specialty: "spine", bodyRegion: "spine", setting: "hospital", addOn: false,
    relatedCodes: ["22802", "22842"], disputeContext: "Deformity correction, very high acuity and value.", valueTier: "high" },
  { code: "22802", codeType: "CPT", slug: "22802", name: "Posterior fusion for spinal deformity, 7 to 12 segments",
    shortDescription: "Posterior fusion to correct a spinal deformity spanning seven to twelve segments.",
    specialty: "spine", bodyRegion: "spine", setting: "hospital", addOn: false,
    relatedCodes: ["22800", "22843"], disputeContext: "Large deformity construct; among the highest value spine cases.", valueTier: "high" },
  { code: "22840", codeType: "CPT", slug: "22840", name: "Posterior nonsegmental spinal instrumentation",
    shortDescription: "Placement of posterior rods anchored only at the ends of the construct.",
    specialty: "spine", bodyRegion: "spine", setting: "hospital", addOn: true,
    relatedCodes: ["22612", "22842"], disputeContext: "Hardware add-on frequently bundled and reduced.", valueTier: "medium" },
  { code: "22843", codeType: "CPT", slug: "22843", name: "Posterior segmental instrumentation, 7 to 12 segments",
    shortDescription: "Placement of posterior rods and screws spanning seven to twelve segments.",
    specialty: "spine", bodyRegion: "spine", setting: "hospital", addOn: true,
    relatedCodes: ["22802"], disputeContext: "Long-construct hardware, high implant value.", valueTier: "high" },
  { code: "22849", codeType: "CPT", slug: "22849", name: "Reinsertion of spinal fixation device",
    shortDescription: "Reinsertion of a spinal fixation device after prior placement.",
    specialty: "spine", bodyRegion: "spine", setting: "hospital", addOn: false,
    relatedCodes: ["22850", "22852"], disputeContext: "Revision hardware work, undervalued by payers.", valueTier: "medium" },
  { code: "22856", codeType: "CPT", slug: "22856", name: "Cervical artificial disc replacement, single level",
    shortDescription: "Replacement of a cervical disc with an artificial disc at one level.",
    specialty: "spine", bodyRegion: "cervical spine", setting: "hospital or ASC", addOn: false,
    relatedCodes: ["22861", "22551"], disputeContext: "Motion-preserving device, high value, frequent prior-auth and payment disputes.", valueTier: "high" },
  { code: "22861", codeType: "CPT", slug: "22861", name: "Revision cervical artificial disc, single level",
    shortDescription: "Revision of a previously placed cervical artificial disc.",
    specialty: "spine", bodyRegion: "cervical spine", setting: "hospital", addOn: false,
    relatedCodes: ["22856"], disputeContext: "Revision device work, undervalued.", valueTier: "high" },
  { code: "22862", codeType: "CPT", slug: "22862", name: "Revision lumbar artificial disc, single level",
    shortDescription: "Revision of a previously placed lumbar artificial disc.",
    specialty: "spine", bodyRegion: "lumbar spine", setting: "hospital", addOn: false,
    relatedCodes: ["22865"], disputeContext: "Revision device work, high acuity.", valueTier: "high" },
  { code: "63001", codeType: "CPT", slug: "63001", name: "Cervical laminectomy for stenosis, 1 to 2 segments",
    shortDescription: "Bone removal to relieve cervical canal narrowing across one to two segments.",
    specialty: "spine", bodyRegion: "cervical spine", setting: "hospital", addOn: false,
    relatedCodes: ["63015", "63045"], disputeContext: "Decompression for stenosis, common out of network.", valueTier: "high" },
  { code: "63005", codeType: "CPT", slug: "63005", name: "Lumbar laminectomy for stenosis, 1 to 2 segments",
    shortDescription: "Bone removal to relieve lumbar canal narrowing across one to two segments.",
    specialty: "spine", bodyRegion: "lumbar spine", setting: "hospital or ASC", addOn: false,
    relatedCodes: ["63017", "63047"], disputeContext: "High volume stenosis decompression.", valueTier: "high" },
  { code: "63015", codeType: "CPT", slug: "63015", name: "Cervical laminectomy for stenosis, more than 2 segments",
    shortDescription: "Multi-level bone removal to relieve cervical canal narrowing.",
    specialty: "spine", bodyRegion: "cervical spine", setting: "hospital", addOn: false,
    relatedCodes: ["63001"], disputeContext: "Multi-level cervical decompression, high value.", valueTier: "high" },
  { code: "63017", codeType: "CPT", slug: "63017", name: "Lumbar laminectomy for stenosis, more than 2 segments",
    shortDescription: "Multi-level bone removal to relieve lumbar canal narrowing.",
    specialty: "spine", bodyRegion: "lumbar spine", setting: "hospital", addOn: false,
    relatedCodes: ["63005"], disputeContext: "Multi-level lumbar decompression.", valueTier: "high" },
  { code: "63020", codeType: "CPT", slug: "63020", name: "Cervical discectomy from the back, single interspace",
    shortDescription: "Posterior removal of a cervical disc with partial bone removal at one interspace.",
    specialty: "spine", bodyRegion: "cervical spine", setting: "hospital", addOn: false,
    relatedCodes: ["63045"], disputeContext: "Posterior cervical disc surgery.", valueTier: "high" },
  { code: "63081", codeType: "CPT", slug: "63081", name: "Anterior cervical corpectomy, single segment",
    shortDescription: "Removal of a cervical vertebral body from the front to decompress the spinal cord.",
    specialty: "spine", bodyRegion: "cervical spine", setting: "hospital", addOn: false,
    relatedCodes: ["63082", "22854"], disputeContext: "High acuity reconstruction, large dollar disputes.", valueTier: "high" },
  { code: "63082", codeType: "CPT", slug: "63082", name: "Anterior cervical corpectomy, each additional segment",
    shortDescription: "Add-on for each additional cervical vertebral body removed from the front.",
    specialty: "spine", bodyRegion: "cervical spine", setting: "hospital", addOn: true,
    relatedCodes: ["63081"], disputeContext: "Per-segment corpectomy add-on.", valueTier: "high" },
  { code: "63090", codeType: "CPT", slug: "63090", name: "Anterior lumbar corpectomy, single segment",
    shortDescription: "Removal of a lumbar vertebral body from the front to decompress the canal.",
    specialty: "spine", bodyRegion: "lumbar spine", setting: "hospital", addOn: false,
    relatedCodes: ["22854"], disputeContext: "High acuity anterior reconstruction.", valueTier: "high" },
  { code: "22511", codeType: "CPT", slug: "22511", name: "Vertebroplasty, lumbosacral",
    shortDescription: "Injection of bone cement into a fractured lumbar or sacral vertebra.",
    specialty: "spine", bodyRegion: "lumbosacral spine", setting: "ASC or hospital", addOn: false,
    relatedCodes: ["22514"], disputeContext: "Fracture stabilization, moderate value.", valueTier: "medium" },
  { code: "22514", codeType: "CPT", slug: "22514", name: "Kyphoplasty, lumbar",
    shortDescription: "Balloon-assisted cement stabilization of a fractured lumbar vertebra.",
    specialty: "spine", bodyRegion: "lumbar spine", setting: "ASC or hospital", addOn: false,
    relatedCodes: ["22511"], disputeContext: "Common fracture procedure, disputed out of network.", valueTier: "medium" },
  { code: "63267", codeType: "CPT", slug: "63267", name: "Lumbar laminectomy for excision of intraspinal lesion",
    shortDescription: "Bone removal to excise a lesion within the lumbar spinal canal.",
    specialty: "spine", bodyRegion: "lumbar spine", setting: "hospital", addOn: false,
    relatedCodes: ["63047"], disputeContext: "Higher acuity than routine decompression.", valueTier: "high" },

  // ---------------------------------------------------------------- ORTHO: shoulder, knee, hip, foot/ankle
  { code: "23410", codeType: "CPT", slug: "23410", name: "Open rotator cuff repair",
    shortDescription: "Open repair of a torn rotator cuff.",
    specialty: "ortho", bodyRegion: "shoulder", setting: "hospital or ASC", addOn: false,
    relatedCodes: ["23412", "29827"], disputeContext: "Open cuff repair, disputed reimbursement out of network.", valueTier: "medium" },
  { code: "23412", codeType: "CPT", slug: "23412", name: "Chronic rotator cuff repair, open",
    shortDescription: "Open repair of a chronic, retracted rotator cuff tear.",
    specialty: "ortho", bodyRegion: "shoulder", setting: "hospital or ASC", addOn: false,
    relatedCodes: ["23410"], disputeContext: "Higher complexity open cuff repair.", valueTier: "medium" },
  { code: "23430", codeType: "CPT", slug: "23430", name: "Biceps tendon repair (tenodesis)",
    shortDescription: "Open reattachment of the long head of the biceps tendon.",
    specialty: "ortho", bodyRegion: "shoulder", setting: "ASC", addOn: false,
    relatedCodes: ["29828"], disputeContext: "Common shoulder procedure.", valueTier: "standard" },
  { code: "29807", codeType: "CPT", slug: "29807", name: "Shoulder arthroscopy with SLAP repair",
    shortDescription: "Arthroscopic repair of a superior labral tear of the shoulder.",
    specialty: "ortho", bodyRegion: "shoulder", setting: "ASC", addOn: false,
    relatedCodes: ["29827"], disputeContext: "Labral repair, sports medicine volume.", valueTier: "medium" },
  { code: "29824", codeType: "CPT", slug: "29824", name: "Shoulder arthroscopy with distal clavicle excision",
    shortDescription: "Arthroscopic removal of the end of the collarbone (Mumford procedure).",
    specialty: "ortho", bodyRegion: "shoulder", setting: "ASC", addOn: false,
    relatedCodes: ["29826"], disputeContext: "Often bundled with cuff repair.", valueTier: "standard" },
  { code: "29828", codeType: "CPT", slug: "29828", name: "Shoulder arthroscopy with biceps tenodesis",
    shortDescription: "Arthroscopic reattachment of the biceps tendon.",
    specialty: "ortho", bodyRegion: "shoulder", setting: "ASC", addOn: false,
    relatedCodes: ["23430"], disputeContext: "Common adjunct to cuff and labral repair.", valueTier: "medium" },
  { code: "29882", codeType: "CPT", slug: "29882", name: "Knee arthroscopy with meniscus repair, single",
    shortDescription: "Arthroscopic repair, rather than removal, of a torn meniscus in one compartment.",
    specialty: "ortho", bodyRegion: "knee", setting: "ASC", addOn: false,
    relatedCodes: ["29883", "29881"], disputeContext: "Meniscus preservation, higher value than meniscectomy.", valueTier: "medium" },
  { code: "29883", codeType: "CPT", slug: "29883", name: "Knee arthroscopy with meniscus repair, both compartments",
    shortDescription: "Arthroscopic repair of torn meniscus in both knee compartments.",
    specialty: "ortho", bodyRegion: "knee", setting: "ASC", addOn: false,
    relatedCodes: ["29882"], disputeContext: "Higher complexity meniscus repair.", valueTier: "medium" },
  { code: "29879", codeType: "CPT", slug: "29879", name: "Knee arthroscopy with microfracture or abrasion",
    shortDescription: "Arthroscopic cartilage stimulation by microfracture or abrasion.",
    specialty: "ortho", bodyRegion: "knee", setting: "ASC", addOn: false,
    relatedCodes: ["29877"], disputeContext: "Cartilage procedure, often bundled.", valueTier: "standard" },
  { code: "29889", codeType: "CPT", slug: "29889", name: "Arthroscopic PCL reconstruction",
    shortDescription: "Arthroscopic reconstruction of the posterior cruciate ligament.",
    specialty: "ortho", bodyRegion: "knee", setting: "ASC or hospital", addOn: false,
    relatedCodes: ["29888"], disputeContext: "High value ligament reconstruction.", valueTier: "medium" },
  { code: "29916", codeType: "CPT", slug: "29916", name: "Hip arthroscopy with labral repair",
    shortDescription: "Arthroscopic repair of the hip labrum.",
    specialty: "ortho", bodyRegion: "hip", setting: "ASC or hospital", addOn: false,
    relatedCodes: ["29914", "29915"], disputeContext: "Growing hip preservation volume; disputed out of network.", valueTier: "medium" },
  { code: "29914", codeType: "CPT", slug: "29914", name: "Hip arthroscopy with femoroplasty",
    shortDescription: "Arthroscopic reshaping of the femoral head and neck for impingement.",
    specialty: "ortho", bodyRegion: "hip", setting: "ASC or hospital", addOn: false,
    relatedCodes: ["29916"], disputeContext: "Hip impingement surgery.", valueTier: "medium" },
  { code: "27407", codeType: "CPT", slug: "27407", name: "Open cruciate ligament repair, knee",
    shortDescription: "Open repair of a cruciate ligament of the knee.",
    specialty: "ortho", bodyRegion: "knee", setting: "hospital or ASC", addOn: false,
    relatedCodes: ["27409", "29888"], disputeContext: "Open ligament repair.", valueTier: "medium" },
  { code: "27488", codeType: "CPT", slug: "27488", name: "Removal of knee replacement components",
    shortDescription: "Removal of the components of a previously replaced knee.",
    specialty: "ortho", bodyRegion: "knee", setting: "hospital", addOn: false,
    relatedCodes: ["27486", "27487"], disputeContext: "Revision-related work, high acuity.", valueTier: "high" },
  { code: "27702", codeType: "CPT", slug: "27702", name: "Total ankle replacement",
    shortDescription: "Replacement of the ankle joint with prosthetic components.",
    specialty: "ortho", bodyRegion: "ankle", setting: "hospital", addOn: false,
    relatedCodes: ["27870"], disputeContext: "Rising volume joint replacement, high device value.", valueTier: "high" },
  { code: "27870", codeType: "CPT", slug: "27870", name: "Ankle fusion",
    shortDescription: "Surgical fusion of the ankle joint.",
    specialty: "ortho", bodyRegion: "ankle", setting: "hospital or ASC", addOn: false,
    relatedCodes: ["27702"], disputeContext: "End-stage ankle arthritis surgery.", valueTier: "medium" },
  { code: "27814", codeType: "CPT", slug: "27814", name: "Ankle fracture repair, bimalleolar",
    shortDescription: "Open repair of a two-part ankle fracture.",
    specialty: "ortho", bodyRegion: "ankle", setting: "hospital or ASC", addOn: false,
    relatedCodes: ["27822"], disputeContext: "Common trauma, emergent out of network exposure.", valueTier: "medium" },
  { code: "27822", codeType: "CPT", slug: "27822", name: "Ankle fracture repair, trimalleolar",
    shortDescription: "Open repair of a three-part ankle fracture.",
    specialty: "ortho", bodyRegion: "ankle", setting: "hospital", addOn: false,
    relatedCodes: ["27814"], disputeContext: "Higher complexity ankle trauma.", valueTier: "medium" },
  { code: "28296", codeType: "CPT", slug: "28296", name: "Bunion correction with osteotomy",
    shortDescription: "Correction of a bunion deformity with a bone cut and realignment.",
    specialty: "ortho", bodyRegion: "foot", setting: "ASC", addOn: false,
    relatedCodes: ["28297"], disputeContext: "High volume foot surgery.", valueTier: "standard" },
  { code: "28297", codeType: "CPT", slug: "28297", name: "Bunion correction with fusion (Lapidus)",
    shortDescription: "Bunion correction with fusion of the first metatarsal base.",
    specialty: "ortho", bodyRegion: "foot", setting: "ASC", addOn: false,
    relatedCodes: ["28296"], disputeContext: "Higher complexity bunion correction.", valueTier: "medium" },
  { code: "24515", codeType: "CPT", slug: "24515", name: "Humerus shaft fracture repair with plate",
    shortDescription: "Open repair of an upper arm shaft fracture with a plate and screws.",
    specialty: "ortho", bodyRegion: "humerus", setting: "hospital", addOn: false,
    relatedCodes: ["23615"], disputeContext: "Long-bone trauma fixation.", valueTier: "medium" },

  // ---------------------------------------------------------------- NEURO: cranial, vascular, functional, nerve
  { code: "61500", codeType: "CPT", slug: "61500", name: "Craniectomy for skull tumor or lesion",
    shortDescription: "Removal of a portion of the skull to excise a bone tumor or lesion.",
    specialty: "neuro", bodyRegion: "skull", setting: "hospital", addOn: false,
    relatedCodes: ["61510"], disputeContext: "High value cranial surgery.", valueTier: "high" },
  { code: "61697", codeType: "CPT", slug: "61697", name: "Surgery for complex intracranial aneurysm",
    shortDescription: "Open surgery to treat a complex aneurysm of a brain artery.",
    specialty: "neuro", bodyRegion: "brain", setting: "hospital", addOn: false,
    relatedCodes: ["61700"], disputeContext: "Among the highest acuity and value codes in medicine.", valueTier: "high" },
  { code: "61700", codeType: "CPT", slug: "61700", name: "Surgery for simple intracranial aneurysm",
    shortDescription: "Open surgery to treat a straightforward aneurysm of a brain artery.",
    specialty: "neuro", bodyRegion: "brain", setting: "hospital", addOn: false,
    relatedCodes: ["61697"], disputeContext: "High value vascular neurosurgery.", valueTier: "high" },
  { code: "61867", codeType: "CPT", slug: "61867", name: "Deep brain stimulator electrode placement",
    shortDescription: "Placement of a deep brain stimulation electrode with physiologic mapping.",
    specialty: "neuro", bodyRegion: "brain", setting: "hospital", addOn: false,
    relatedCodes: ["61885"], disputeContext: "High device value functional neurosurgery.", valueTier: "high" },
  { code: "61885", codeType: "CPT", slug: "61885", name: "Cranial neurostimulator generator placement",
    shortDescription: "Insertion of the pulse generator that powers a cranial neurostimulator.",
    specialty: "neuro", bodyRegion: "brain", setting: "hospital", addOn: false,
    relatedCodes: ["61867"], disputeContext: "Implant-heavy, large dollar disputes.", valueTier: "high" },
  { code: "62230", codeType: "CPT", slug: "62230", name: "Shunt revision or replacement",
    shortDescription: "Revision or replacement of a cerebrospinal fluid shunt.",
    specialty: "neuro", bodyRegion: "brain", setting: "hospital", addOn: false,
    relatedCodes: ["62223"], disputeContext: "Common revision procedure.", valueTier: "medium" },
  { code: "62201", codeType: "CPT", slug: "62201", name: "Endoscopic third ventriculostomy",
    shortDescription: "Endoscopic creation of a drainage pathway for cerebrospinal fluid.",
    specialty: "neuro", bodyRegion: "brain", setting: "hospital", addOn: false,
    relatedCodes: ["62223"], disputeContext: "Alternative to shunting, high acuity.", valueTier: "high" },
  { code: "64712", codeType: "CPT", slug: "64712", name: "Sciatic nerve decompression",
    shortDescription: "Surgical decompression or repair of the sciatic nerve.",
    specialty: "neuro", bodyRegion: "leg", setting: "hospital or ASC", addOn: false,
    relatedCodes: ["64708"], disputeContext: "Major nerve decompression.", valueTier: "medium" },
  { code: "64713", codeType: "CPT", slug: "64713", name: "Brachial plexus decompression",
    shortDescription: "Surgical decompression or repair of the brachial plexus.",
    specialty: "neuro", bodyRegion: "shoulder/arm", setting: "hospital", addOn: false,
    relatedCodes: ["64708"], disputeContext: "Complex nerve surgery, high value.", valueTier: "high" },
  { code: "64856", codeType: "CPT", slug: "64856", name: "Major nerve repair, arm or leg",
    shortDescription: "Microsurgical repair of a major peripheral nerve in the arm or leg.",
    specialty: "neuro", bodyRegion: "extremity", setting: "hospital", addOn: false,
    relatedCodes: ["64910"], disputeContext: "Nerve repair, high acuity.", valueTier: "high" },
  { code: "64910", codeType: "CPT", slug: "64910", name: "Nerve repair with graft",
    shortDescription: "Repair of a peripheral nerve using a nerve graft.",
    specialty: "neuro", bodyRegion: "extremity", setting: "hospital", addOn: false,
    relatedCodes: ["64856"], disputeContext: "Grafted nerve repair, highest nerve value tier.", valueTier: "high" },
  { code: "64704", codeType: "CPT", slug: "64704", name: "Nerve decompression, hand or foot",
    shortDescription: "Surgical decompression of a nerve in the hand or foot.",
    specialty: "neuro", bodyRegion: "hand/foot", setting: "ASC or office", addOn: false,
    relatedCodes: ["64721"], disputeContext: "Common smaller nerve procedure.", valueTier: "standard" },

  // ---------------------------------------------------------------- PLASTICS: grafts, flaps, breast, hand
  { code: "15100", codeType: "CPT", slug: "15100", name: "Split thickness skin graft, trunk or extremity",
    shortDescription: "Transfer of a thin skin graft to cover a wound on the trunk or limb.",
    specialty: "plastics", bodyRegion: "trunk/extremity", setting: "hospital or ASC", addOn: false,
    relatedCodes: ["15240"], disputeContext: "Common reconstruction, frequently delivered out of network.", valueTier: "medium" },
  { code: "15240", codeType: "CPT", slug: "15240", name: "Full thickness skin graft, face or extremity",
    shortDescription: "Transfer of a full thickness skin graft to cover a defect.",
    specialty: "plastics", bodyRegion: "face/extremity", setting: "hospital or ASC", addOn: false,
    relatedCodes: ["15100"], disputeContext: "Higher complexity graft.", valueTier: "medium" },
  { code: "15757", codeType: "CPT", slug: "15757", name: "Free skin flap with microvascular repair",
    shortDescription: "Transfer of a free skin flap reconnected with microsurgical vessel repair.",
    specialty: "plastics", bodyRegion: "varies", setting: "hospital", addOn: false,
    relatedCodes: ["15756", "15758"], disputeContext: "Microsurgical reconstruction, highest value tier.", valueTier: "high" },
  { code: "15758", codeType: "CPT", slug: "15758", name: "Free fascial flap with microvascular repair",
    shortDescription: "Transfer of a free fascial flap reconnected with microsurgical vessel repair.",
    specialty: "plastics", bodyRegion: "varies", setting: "hospital", addOn: false,
    relatedCodes: ["15757"], disputeContext: "Microsurgical reconstruction.", valueTier: "high" },
  { code: "15750", codeType: "CPT", slug: "15750", name: "Neurovascular pedicle flap",
    shortDescription: "Transfer of a flap carrying its own nerve and blood supply.",
    specialty: "plastics", bodyRegion: "varies", setting: "hospital", addOn: false,
    relatedCodes: ["15740"], disputeContext: "Specialized flap reconstruction.", valueTier: "high" },
  { code: "15740", codeType: "CPT", slug: "15740", name: "Island pedicle flap",
    shortDescription: "Transfer of a flap on a defined vascular pedicle to close a defect.",
    specialty: "plastics", bodyRegion: "varies", setting: "hospital or ASC", addOn: false,
    relatedCodes: ["15750"], disputeContext: "Pedicled reconstruction.", valueTier: "medium" },
  { code: "19340", codeType: "CPT", slug: "19340", name: "Immediate breast implant placement",
    shortDescription: "Placement of a breast implant at the time of mastectomy.",
    specialty: "plastics", bodyRegion: "breast", setting: "hospital", addOn: false,
    relatedCodes: ["19342", "19357"], disputeContext: "Post-mastectomy reconstruction, protected and high value.", valueTier: "high" },
  { code: "19342", codeType: "CPT", slug: "19342", name: "Delayed breast implant placement",
    shortDescription: "Placement of a breast implant in a delayed reconstruction.",
    specialty: "plastics", bodyRegion: "breast", setting: "hospital", addOn: false,
    relatedCodes: ["19340"], disputeContext: "Reconstruction, high value.", valueTier: "high" },
  { code: "19350", codeType: "CPT", slug: "19350", name: "Nipple and areola reconstruction",
    shortDescription: "Surgical reconstruction of the nipple and areola.",
    specialty: "plastics", bodyRegion: "breast", setting: "ASC or office", addOn: false,
    relatedCodes: ["19357"], disputeContext: "Final stage breast reconstruction.", valueTier: "standard" },
  { code: "19371", codeType: "CPT", slug: "19371", name: "Breast implant capsule removal",
    shortDescription: "Surgical removal of the scar capsule around a breast implant.",
    specialty: "plastics", bodyRegion: "breast", setting: "hospital or ASC", addOn: false,
    relatedCodes: ["19370", "19380"], disputeContext: "Revision reconstruction.", valueTier: "medium" },
  { code: "19380", codeType: "CPT", slug: "19380", name: "Revision of reconstructed breast",
    shortDescription: "Revision of a previously reconstructed breast.",
    specialty: "plastics", bodyRegion: "breast", setting: "hospital or ASC", addOn: false,
    relatedCodes: ["19371"], disputeContext: "Revision work, undervalued by payers.", valueTier: "medium" },
  { code: "13132", codeType: "CPT", slug: "13132", name: "Complex wound repair, face",
    shortDescription: "Layered repair of a complex facial wound.",
    specialty: "plastics", bodyRegion: "face", setting: "ASC or office", addOn: false,
    relatedCodes: ["14060"], disputeContext: "Often delivered emergently and out of network.", valueTier: "standard" },
  { code: "14060", codeType: "CPT", slug: "14060", name: "Tissue transfer, eyelid, nose, or lip",
    shortDescription: "Local tissue rearrangement to close a defect on the eyelid, nose, or lip.",
    specialty: "plastics", bodyRegion: "face", setting: "ASC or office", addOn: false,
    relatedCodes: ["13132"], disputeContext: "Facial reconstruction.", valueTier: "medium" },
  { code: "26055", codeType: "CPT", slug: "26055", name: "Trigger finger release",
    shortDescription: "Release of the tendon sheath to relieve a trigger finger.",
    specialty: "plastics", bodyRegion: "hand", setting: "office or ASC", addOn: false,
    relatedCodes: ["64721"], disputeContext: "High volume hand procedure.", valueTier: "standard" },

  // ---------------------------------------------------------------- PAIN: transforaminal, facet add-ons, SI, pumps
  { code: "64479", codeType: "CPT", slug: "64479", name: "Transforaminal epidural injection, cervical, single level",
    shortDescription: "Targeted steroid injection around a single cervical nerve root through the foramen.",
    specialty: "pain", bodyRegion: "cervical spine", setting: "ASC or office", addOn: false,
    relatedCodes: ["64480", "64483"], disputeContext: "Cervical interventional pain code, high frequency.", valueTier: "standard" },
  { code: "64480", codeType: "CPT", slug: "64480", name: "Transforaminal epidural injection, cervical, each additional level",
    shortDescription: "Add-on for each additional cervical nerve root injected in the same session.",
    specialty: "pain", bodyRegion: "cervical spine", setting: "ASC or office", addOn: true,
    relatedCodes: ["64479"], disputeContext: "Per-level add-on, bundled by payers.", valueTier: "standard" },
  { code: "64491", codeType: "CPT", slug: "64491", name: "Facet joint injection, cervical, second level",
    shortDescription: "Add-on injection of a second cervical or thoracic facet joint level.",
    specialty: "pain", bodyRegion: "cervical/thoracic spine", setting: "ASC or office", addOn: true,
    relatedCodes: ["64490"], disputeContext: "Per-level facet add-on.", valueTier: "standard" },
  { code: "64494", codeType: "CPT", slug: "64494", name: "Facet joint injection, lumbar, second level",
    shortDescription: "Add-on injection of a second lumbar or sacral facet joint level.",
    specialty: "pain", bodyRegion: "lumbar/sacral spine", setting: "ASC or office", addOn: true,
    relatedCodes: ["64493"], disputeContext: "Per-level facet add-on.", valueTier: "standard" },
  { code: "64634", codeType: "CPT", slug: "64634", name: "Facet radiofrequency ablation, cervical, each additional",
    shortDescription: "Add-on heat lesioning of each additional cervical or thoracic facet level.",
    specialty: "pain", bodyRegion: "cervical/thoracic spine", setting: "ASC", addOn: true,
    relatedCodes: ["64633"], disputeContext: "Per-level ablation add-on.", valueTier: "standard" },
  { code: "27096", codeType: "CPT", slug: "27096", name: "Sacroiliac joint injection with imaging",
    shortDescription: "Image-guided injection into the sacroiliac joint.",
    specialty: "pain", bodyRegion: "sacroiliac joint", setting: "ASC or office", addOn: false,
    relatedCodes: ["64451", "64625"], disputeContext: "Common low back and pelvis pain procedure.", valueTier: "standard" },
  { code: "64451", codeType: "CPT", slug: "64451", name: "Injection of nerves of the sacroiliac joint",
    shortDescription: "Injection of the nerves that supply the sacroiliac joint with imaging.",
    specialty: "pain", bodyRegion: "sacroiliac joint", setting: "ASC or office", addOn: false,
    relatedCodes: ["64625"], disputeContext: "Diagnostic step before SI ablation.", valueTier: "standard" },
  { code: "64625", codeType: "CPT", slug: "64625", name: "Radiofrequency ablation of sacroiliac joint nerves",
    shortDescription: "Heat lesioning of the nerves that supply the sacroiliac joint.",
    specialty: "pain", bodyRegion: "sacroiliac joint", setting: "ASC", addOn: false,
    relatedCodes: ["64451"], disputeContext: "Higher value SI ablation.", valueTier: "medium" },
  { code: "27279", codeType: "CPT", slug: "27279", name: "Minimally invasive sacroiliac joint fusion",
    shortDescription: "Percutaneous fusion of the sacroiliac joint with implants.",
    specialty: "pain", bodyRegion: "sacroiliac joint", setting: "ASC or hospital", addOn: false,
    relatedCodes: ["27280"], disputeContext: "Growing volume with high device value; frequent payment disputes.", valueTier: "high" },
  { code: "62350", codeType: "CPT", slug: "62350", name: "Intrathecal pump catheter implantation",
    shortDescription: "Placement of a catheter for an implanted drug delivery pump.",
    specialty: "pain", bodyRegion: "spine", setting: "ASC or hospital", addOn: false,
    relatedCodes: ["62362"], disputeContext: "Device-related pain management.", valueTier: "medium" },
  { code: "62362", codeType: "CPT", slug: "62362", name: "Implantation of intrathecal infusion pump",
    shortDescription: "Insertion of an implanted pump for spinal drug delivery.",
    specialty: "pain", bodyRegion: "spine", setting: "ASC or hospital", addOn: false,
    relatedCodes: ["62350"], disputeContext: "High device value implant.", valueTier: "high" },
  { code: "63661", codeType: "CPT", slug: "63661", name: "Removal of spinal neurostimulator electrode, percutaneous",
    shortDescription: "Removal of a percutaneously placed spinal neurostimulator electrode.",
    specialty: "pain", bodyRegion: "spine", setting: "ASC", addOn: false,
    relatedCodes: ["63650"], disputeContext: "Revision-related stimulator work.", valueTier: "medium" },
  // ---------------------------------------------------------------- FINAL EXPANSION (to full disputed surgical set)
  { code: "63050", codeType: "CPT", slug: "63050", name: "Cervical laminoplasty, 2 or more segments",
    shortDescription: "Reshaping of the cervical laminae to enlarge the spinal canal across two or more segments.",
    specialty: "spine", bodyRegion: "cervical spine", setting: "hospital", addOn: false,
    relatedCodes: ["63015"], disputeContext: "Motion-sparing decompression, high value.", valueTier: "high" },
  { code: "63055", codeType: "CPT", slug: "63055", name: "Thoracic transpedicular decompression, single segment",
    shortDescription: "Decompression of the thoracic canal through the pedicle at one segment.",
    specialty: "spine", bodyRegion: "thoracic spine", setting: "hospital", addOn: false,
    relatedCodes: ["63056"], disputeContext: "High acuity thoracic decompression.", valueTier: "high" },
  { code: "63064", codeType: "CPT", slug: "63064", name: "Thoracic costovertebral decompression, single segment",
    shortDescription: "Decompression of the thoracic canal by a costovertebral approach at one segment.",
    specialty: "spine", bodyRegion: "thoracic spine", setting: "hospital", addOn: false,
    relatedCodes: ["63055"], disputeContext: "Specialized thoracic approach.", valueTier: "high" },
  { code: "22852", codeType: "CPT", slug: "22852", name: "Removal of posterior segmental instrumentation",
    shortDescription: "Removal of posterior segmental spinal hardware.",
    specialty: "spine", bodyRegion: "spine", setting: "hospital", addOn: false,
    relatedCodes: ["22842"], disputeContext: "Revision-related hardware removal.", valueTier: "medium" },
  { code: "62380", codeType: "CPT", slug: "62380", name: "Endoscopic lumbar decompression, single interspace",
    shortDescription: "Endoscopic removal of disc or bone to decompress a lumbar interspace.",
    specialty: "spine", bodyRegion: "lumbar spine", setting: "ASC or hospital", addOn: false,
    relatedCodes: ["63030"], disputeContext: "Growing endoscopic volume, disputed reimbursement.", valueTier: "medium" },
  { code: "23420", codeType: "CPT", slug: "23420", name: "Repair of complete shoulder cuff avulsion, chronic",
    shortDescription: "Open repair of a chronic complete avulsion of the rotator cuff.",
    specialty: "ortho", bodyRegion: "shoulder", setting: "hospital or ASC", addOn: false,
    relatedCodes: ["23412"], disputeContext: "Complex chronic cuff repair.", valueTier: "medium" },
  { code: "27425", codeType: "CPT", slug: "27425", name: "Lateral retinacular release, open",
    shortDescription: "Open release of the lateral retinaculum of the knee.",
    specialty: "ortho", bodyRegion: "knee", setting: "ASC", addOn: false,
    relatedCodes: ["27427"], disputeContext: "Patellar realignment procedure.", valueTier: "standard" },
  { code: "27427", codeType: "CPT", slug: "27427", name: "Knee ligament reconstruction, extra-articular",
    shortDescription: "Reconstruction of a knee ligament outside the joint.",
    specialty: "ortho", bodyRegion: "knee", setting: "ASC or hospital", addOn: false,
    relatedCodes: ["27428"], disputeContext: "Ligament reconstruction.", valueTier: "medium" },
  { code: "27428", codeType: "CPT", slug: "27428", name: "Knee ligament reconstruction, intra-articular",
    shortDescription: "Reconstruction of a knee ligament inside the joint.",
    specialty: "ortho", bodyRegion: "knee", setting: "ASC or hospital", addOn: false,
    relatedCodes: ["27427"], disputeContext: "Higher complexity ligament reconstruction.", valueTier: "medium" },
  { code: "27758", codeType: "CPT", slug: "27758", name: "Tibia shaft fracture repair with plate",
    shortDescription: "Open repair of a tibial shaft fracture with a plate and screws.",
    specialty: "ortho", bodyRegion: "tibia", setting: "hospital", addOn: false,
    relatedCodes: ["27759"], disputeContext: "Long-bone trauma fixation.", valueTier: "medium" },
  { code: "27766", codeType: "CPT", slug: "27766", name: "Medial malleolus fracture repair",
    shortDescription: "Open repair of a fracture of the inner ankle bone.",
    specialty: "ortho", bodyRegion: "ankle", setting: "hospital or ASC", addOn: false,
    relatedCodes: ["27814"], disputeContext: "Ankle trauma fixation.", valueTier: "standard" },
  { code: "27784", codeType: "CPT", slug: "27784", name: "Fibula fracture repair",
    shortDescription: "Open repair of a fibula fracture with fixation.",
    specialty: "ortho", bodyRegion: "fibula", setting: "hospital or ASC", addOn: false,
    relatedCodes: ["27814"], disputeContext: "Lower leg trauma fixation.", valueTier: "standard" },
  { code: "26615", codeType: "CPT", slug: "26615", name: "Metacarpal fracture repair",
    shortDescription: "Open repair of a hand metacarpal fracture with fixation.",
    specialty: "ortho", bodyRegion: "hand", setting: "ASC or office", addOn: false,
    relatedCodes: ["26746"], disputeContext: "Hand trauma fixation.", valueTier: "standard" },
  { code: "26746", codeType: "CPT", slug: "26746", name: "Finger fracture repair, intra-articular",
    shortDescription: "Open repair of a finger fracture involving the joint surface.",
    specialty: "ortho", bodyRegion: "hand", setting: "ASC or office", addOn: false,
    relatedCodes: ["26615"], disputeContext: "Hand trauma fixation.", valueTier: "standard" },
  { code: "24360", codeType: "CPT", slug: "24360", name: "Elbow joint resurfacing arthroplasty",
    shortDescription: "Resurfacing arthroplasty of the elbow joint.",
    specialty: "ortho", bodyRegion: "elbow", setting: "hospital", addOn: false,
    relatedCodes: ["24363"], disputeContext: "Lower volume joint reconstruction.", valueTier: "medium" },
  { code: "61322", codeType: "CPT", slug: "61322", name: "Decompressive craniectomy with lobectomy",
    shortDescription: "Removal of a portion of the skull and brain tissue to relieve pressure.",
    specialty: "neuro", bodyRegion: "brain", setting: "hospital", addOn: false,
    relatedCodes: ["61304"], disputeContext: "Emergent cranial decompression, NSA-protected.", valueTier: "high" },
  { code: "62164", codeType: "CPT", slug: "62164", name: "Neuroendoscopic excision of brain tumor",
    shortDescription: "Endoscopic removal of a brain tumor.",
    specialty: "neuro", bodyRegion: "brain", setting: "hospital", addOn: false,
    relatedCodes: ["61510"], disputeContext: "High value cranial surgery.", valueTier: "high" },
  { code: "64727", codeType: "CPT", slug: "64727", name: "Internal neurolysis with nerve microdissection",
    shortDescription: "Add-on microdissection within a nerve to free entrapped fibers.",
    specialty: "neuro", bodyRegion: "varies", setting: "ASC or hospital", addOn: true,
    relatedCodes: ["64721", "69990"], disputeContext: "Add-on routinely bundled and reduced.", valueTier: "standard" },
  { code: "19316", codeType: "CPT", slug: "19316", name: "Breast lift (mastopexy), reconstruction context",
    shortDescription: "Surgical lift of the breast, in a reconstruction context.",
    specialty: "plastics", bodyRegion: "breast", setting: "ASC or hospital", addOn: false,
    relatedCodes: ["19380"], disputeContext: "Reconstruction symmetry procedure.", valueTier: "standard" },
  { code: "15877", codeType: "CPT", slug: "15877", name: "Suction-assisted lipectomy, trunk, reconstruction context",
    shortDescription: "Contour correction of the trunk by suction-assisted lipectomy in a reconstruction context.",
    specialty: "plastics", bodyRegion: "trunk", setting: "ASC or hospital", addOn: false,
    relatedCodes: ["15734"], disputeContext: "Reconstruction adjunct; confirm medical necessity.", valueTier: "standard" },
  { code: "11043", codeType: "CPT", slug: "11043", name: "Debridement of muscle and fascia",
    shortDescription: "Surgical removal of dead muscle and fascia from a wound.",
    specialty: "plastics", bodyRegion: "varies", setting: "hospital or ASC", addOn: false,
    relatedCodes: ["13101"], disputeContext: "Often delivered emergently and out of network.", valueTier: "standard" },
  { code: "G0260", codeType: "HCPCS", slug: "g0260", name: "Sacroiliac joint injection, facility add-on",
    shortDescription: "Facility coding for sacroiliac joint arthrography injection.",
    specialty: "pain", bodyRegion: "sacroiliac joint", setting: "ASC", addOn: false,
    relatedCodes: ["27096"], disputeContext: "Public domain HCPCS code; confirm facility context.", valueTier: "standard" },
  { code: "62322", codeType: "CPT", slug: "62322", name: "Lumbar epidural injection without imaging",
    shortDescription: "Epidural steroid injection in the low back performed without image guidance.",
    specialty: "pain", bodyRegion: "lumbar spine", setting: "office or ASC", addOn: false,
    relatedCodes: ["62323"], disputeContext: "High volume pain procedure.", valueTier: "standard" },
  { code: "62320", codeType: "CPT", slug: "62320", name: "Cervical epidural injection without imaging",
    shortDescription: "Epidural steroid injection in the neck performed without image guidance.",
    specialty: "pain", bodyRegion: "cervical spine", setting: "office or ASC", addOn: false,
    relatedCodes: ["62321"], disputeContext: "Common pain procedure.", valueTier: "standard" },
  { code: "27280", codeType: "CPT", slug: "27280", name: "Open sacroiliac joint fusion",
    shortDescription: "Open surgical fusion of the sacroiliac joint.",
    specialty: "pain", bodyRegion: "sacroiliac joint", setting: "hospital", addOn: false,
    relatedCodes: ["27279"], disputeContext: "Higher acuity SI fusion.", valueTier: "high" },
  { code: "64681", codeType: "CPT", slug: "64681", name: "Neurolytic celiac plexus block",
    shortDescription: "Destruction of the celiac plexus nerves for abdominal pain.",
    specialty: "pain", bodyRegion: "abdomen", setting: "ASC or hospital", addOn: false,
    relatedCodes: [], disputeContext: "Specialized pain procedure, often cancer related.", valueTier: "medium" },
  { code: "63662", codeType: "CPT", slug: "63662", name: "Revision of spinal neurostimulator electrode plate",
    shortDescription: "Revision or replacement of a surgically placed neurostimulator electrode plate.",
    specialty: "spine", bodyRegion: "spine", setting: "hospital", addOn: false,
    relatedCodes: ["63655"], disputeContext: "Revision device work.", valueTier: "medium" },
];

// Convenience selectors over the source code spine.
export const SOURCE_CODE_SLUGS = SOURCE_CODES.map((c) => c.slug);
export const sourceCodeBySlug = (slug: string) =>
  SOURCE_CODES.find((c) => c.slug === slug);
export const sourceCodesBySpecialty = (s: SourceSpecialty) =>
  SOURCE_CODES.filter((c) => c.specialty === s);
